const KEY = 'bookmarks-admin-tabs-v2';
const $ = (id) => document.getElementById(id);
const $$ = (s, r=document) => [...r.querySelectorAll(s)];
const esc = (v) => String(v ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const js = (v) => `"${String(v ?? '').replace(/\\/g,'\\\\').replace(/"/g,'\\"').replace(/\r?\n/g,' ').trim()}"`;
const sq = (v) => `'${String(v ?? '').replace(/\\/g,'\\\\').replace(/'/g,"\\'").replace(/\r?\n/g,' ').trim()}'`;
const slug = (v) => String(v || 'creator').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'') || 'creator';
const urlOk = (v) => !v || v === '#' || /^(https?:\/\/|\/|mailto:|ipfs:\/\/|ftp:\/\/)/i.test(v);

const PAGES = {
  home:{label:'Home / Hub data',file:'data/bookmarks-data.js',array:'window.BOOKMARKS_DATA'},
  docs:{label:'Docs',file:'docs.html',array:'const docsData'},
  files:{label:'Files',file:'files.html',array:'const docsData'},
  jobs:{label:'Jobs',file:'jobs.html',array:'const docsData'},
  news:{label:'News',file:'news.html',array:'HTML glass-card blocks'},
  hub:{label:'Hub',file:'hub.html',array:'const featuredData'},
  creators:{label:'Creators',file:'creators.html',array:'const CREATORS_DATA'},
  about:{label:'About',file:'about.html',array:'HTML content block'},
  privacy:{label:'Privacy',file:'privacy.html',array:'HTML content block'},
  terms:{label:'Terms',file:'terms.html',array:'HTML content block'},
  join:{label:'Join',file:'join.html',array:'HTML content block'},
  edit:{label:'Edit',file:'edit.html',array:'HTML content block'},
  custom:{label:'Custom same-format page',file:'custom page',array:'same-format block'}
};
const ICONS = ['file-text','download','github','users','briefcase','newspaper','heart','search','shield','book-open','globe','terminal'];
const TYPES = {
  resource:{label:'Site / resource link',target:'Home, Docs, Files, Jobs and similar pages',help:'Creates the { name, link, desc, cat } format. Draft tabs split by page + category so you never paste unrelated categories together.',fields:[['page','selectPage','Target page'],['category','text','Category'],['name','text','Site name'],['link','url','URL'],['desc','textarea','Description']]},
  creatorCard:{label:'Creator card',target:'creators.html → CREATORS_DATA',help:'One creator listing object.',fields:[['id','number','ID'],['name','text','Creator name'],['handle','text','Handle'],['initials','text','Initials'],['avatar','text','Avatar path'],['verified','checkbox','Verified'],['category','text','Category'],['bio','textarea','Bio'],['links','number','Links count'],['url','text','Profile URL'],['x','url','X / Twitter'],['youtube','url','YouTube'],['github','url','GitHub'],['website','url','Website'],['spotify','url','Spotify'],['apple_podcast','url','Apple Podcast']]},
  profileHeader:{label:'Creator profile header',target:'creator profile page HTML',help:'Profile header block for a page based on creators/profiletemplate.html.',fields:[['creator','text','Creator name'],['handle','text','Handle'],['avatar','text','Avatar path'],['x','url','X link'],['youtube','url','YouTube link'],['github','url','GitHub link'],['website','url','Website link']]},
  profileResource:{label:'Creator profile resource',target:'creator profile page → collectionData',help:'Resource item grouped in the selected creator profile collectionData. Tabs split by creator.',fields:[['creator','text','Creator / profile'],['section','text','Section title'],['name','text','Resource name'],['desc','textarea','Description'],['img','text','Image path'],['url','url','URL'],['tag','text','Tag']]},
  hubTile:{label:'Hub tile',target:'hub.html → featuredData',help:'One tile for the hub featuredData array.',fields:[['name','text','Tile name'],['desc','text','Short description'],['link','url','Link'],['icon','selectIcon','Icon'],['size','selectSize','Size']]},
  newsBlock:{label:'News changelog post',target:'news.html → Project Changelog',help:'A .glass-card update for the changelog section.',fields:[['title','text','Title'],['date','date','Date'],['body','textarea','Body paragraph'],['body2','textarea','Optional second paragraph'],['link','url','Optional link']]},
  newsSource:{label:'News source card',target:'news.html → news-grid',help:'One external source card for the curated news directory.',fields:[['title','text','Source category title'],['desc','textarea','Description'],['link','url','Link'],['count','text','Source count label'],['accent','selectAccent','Accent color']]},
  pageSection:{label:'Generic page section',target:'Any HTML page → content area',help:'Reusable section/glass-card for static content pages. Tabs split by target page.',fields:[['page','selectAnyPage','Target page'],['kicker','text','Small kicker'],['title','text','Title'],['body','textarea','Body paragraph'],['list','textarea','Optional bullet list, one per line'],['link','url','Optional link'],['linkLabel','text','Link label']]},
  navItem:{label:'Navigation / menu item',target:'Header or hamburger menu HTML',help:'Menu item block for headers/hamburger menus.',fields:[['title','text','Menu title'],['desc','text','Menu description'],['href','url','Href'],['icon','selectIcon','Icon']]}
};
function fresh(){return{currentType:'resource',activeGroup:'',drafts:[],form:{resource:{page:'home',category:'Search',name:'',link:'https://',desc:''},creatorCard:{id:1,name:'',handle:'@',initials:'',avatar:'/creators/img/avatar.jpg',verified:true,category:'Security',bio:'',links:0,url:'/creators/creator.html',x:'#',youtube:'#',github:'#',website:'#',spotify:'#',apple_podcast:'#'},profileHeader:{creator:'',handle:'@',avatar:'/creators/img/avatar.jpg',x:'#',youtube:'#',github:'#',website:'#'},profileResource:{creator:'',section:'Getting Started',name:'',desc:'',img:'',url:'#',tag:'Guide'},hubTile:{name:'',desc:'',link:'',icon:'file-text',size:''},newsBlock:{title:'',date:new Date().toISOString().slice(0,10),body:'',body2:'',link:''},newsSource:{title:'Tech Industry',desc:'Latest developments and trusted sources.',link:'#',count:'50+ Sources',accent:'blue'},pageSection:{page:'about',kicker:'Section',title:'New Section',body:'Write the main paragraph here.',list:'',link:'',linkLabel:'Learn more'},navItem:{title:'New Page',desc:'Short description',href:'page.html',icon:'file-text'}}};}
function merge(a,b){for(const k in b){if(b[k]&&typeof b[k]==='object'&&!Array.isArray(b[k]))a[k]=merge(a[k]||{},b[k]);else a[k]=b[k]}return a}
let state = (()=>{try{return merge(fresh(), JSON.parse(localStorage.getItem(KEY)||'{}'))}catch{return fresh()}})();
const save = () => {localStorage.setItem(KEY, JSON.stringify(state)); render();};
const current = () => state.form[state.currentType];

function fieldHtml([key,type,label]){const v=current()[key] ?? ''; if(type==='textarea')return `<label>${label}<textarea data-field="${key}">${esc(v)}</textarea></label>`; if(type==='checkbox')return `<label class="check"><input type="checkbox" data-field="${key}" ${v?'checked':''}> ${label}</label>`; if(type==='selectPage'||type==='selectAnyPage')return `<label>${label}<select data-field="${key}">${Object.entries(PAGES).map(([k,p])=>`<option value="${k}" ${v===k?'selected':''}>${esc(p.label)}</option>`).join('')}</select></label>`; if(type==='selectIcon')return `<label>${label}<select data-field="${key}">${ICONS.map(i=>`<option value="${i}" ${v===i?'selected':''}>${i}</option>`).join('')}</select></label>`; if(type==='selectAccent')return `<label>${label}<select data-field="${key}">${['blue','red','green','purple','yellow'].map(i=>`<option value="${i}" ${v===i?'selected':''}>${i}</option>`).join('')}</select></label>`; if(type==='selectSize')return `<label>${label}<select data-field="${key}"><option value="" ${!v?'selected':''}>Normal</option><option value="large" ${v==='large'?'selected':''}>Large</option></select></label>`; return `<label>${label}<input data-field="${key}" type="${type==='number'?'number':type==='date'?'date':'text'}" value="${esc(v)}"></label>`;}
function groupMeta(d){const x=d.data||{}; if(d.type==='resource')return{key:`resource:${x.page||'home'}:${x.category||'Uncategorized'}`,label:`${PAGES[x.page]?.label||x.page||'Page'} / ${x.category||'Uncategorized'}`,target:`${PAGES[x.page]?.file||'custom page'} → ${PAGES[x.page]?.array||'data array'}`}; if(d.type==='creatorCard')return{key:'creatorCard:creators',label:'Creators listing',target:'creators.html → CREATORS_DATA'}; if(d.type==='profileHeader')return{key:`profileHeader:${slug(x.creator)}`,label:`Profile header / ${x.creator||'creator'}`,target:`creators/${slug(x.creator)}.html → profile section`}; if(d.type==='profileResource')return{key:`profileResource:${slug(x.creator)}`,label:`Profile resources / ${x.creator||'creator'}`,target:`creators/${slug(x.creator)}.html → collectionData`}; if(d.type==='hubTile')return{key:'hubTile:hub',label:'Hub tiles',target:'hub.html → featuredData'}; if(d.type==='newsBlock')return{key:'newsBlock:changelog',label:'News changelog',target:'news.html → Project Changelog'}; if(d.type==='newsSource')return{key:'newsSource:grid',label:'News sources grid',target:'news.html → news-grid'}; if(d.type==='pageSection')return{key:`pageSection:${x.page||'custom'}`,label:`Page section / ${PAGES[x.page]?.label||x.page||'custom'}`,target:`${PAGES[x.page]?.file||'custom page'} → content area`}; if(d.type==='navItem')return{key:'navItem:menu',label:'Navigation/menu items',target:'header or hamburger menu'}; return{key:d.type,label:TYPES[d.type]?.label||d.type,target:TYPES[d.type]?.target||''};}
function groupedDrafts(){const m=new Map();(state.drafts||[]).forEach((d,i)=>{if(!d||!d.type||!TYPES[d.type]||!d.data)return;const g=groupMeta(d); if(!g||!g.key)return; if(!m.has(g.key))m.set(g.key,{...g,items:[]}); m.get(g.key).items.push({d,i});}); return [...m.values()];}
function activeGroup(){const groups=groupedDrafts(); if(!groups.length){state.activeGroup='';return null;} if(state.activeGroup==='__all')return {key:'__all',label:'All tabs',target:'all targets',items:(state.drafts||[]).map((d,i)=>({d,i})).filter(x=>x.d&&TYPES[x.d.type])}; if(!state.activeGroup||!groups.some(g=>g.key===state.activeGroup))state.activeGroup=groups[0].key; return groups.find(g=>g.key===state.activeGroup)||groups[0];}
function group(arr,fn){return arr.reduce((a,x)=>{const k=fn(x)||'Other';(a[k]||=[]).push(x);return a},{})}

function renderCodeTabs(){
  const root=$('codeTabs'); if(!root)return;
  const groups=groupedDrafts();
  if(!groups.length){root.innerHTML='<div class="code-tab-empty"><span></span><span></span><span></span>No draft tabs yet ? add a block to create one.</div>';return;}
  if(!state.activeGroup||(!groups.some(g=>g.key===state.activeGroup)&&state.activeGroup!=='__all')) state.activeGroup=groups[0].key;
  const tabs=groups.map(g=>'<button type="button" class="code-tab '+(g.key===state.activeGroup?'active':'')+'" data-codegroup="'+esc(g.key)+'"><span class="dot"></span><span class="tab-title">'+esc(g.label)+'</span><b>'+g.items.length+'</b></button>').join('');
  const all=groups.length>1?'<button type="button" class="code-tab all '+(state.activeGroup==='__all'?'active':'')+'" data-codegroup="__all"><span class="dot"></span><span class="tab-title">All tabs</span><b>'+state.drafts.length+'</b></button>':'';
  root.innerHTML=tabs+all;
  $('[data-codegroup]',root).forEach(btn=>btn.onclick=(ev)=>{ev.preventDefault();state.activeGroup=btn.dataset.codegroup;localStorage.setItem(KEY,JSON.stringify(state));renderCodeTabs();renderDrafts();renderOutput();pulseCode();});
}
function pulseCode(){const el=$('code'); if(!el)return; el.classList.remove('code-swap'); void el.offsetWidth; el.classList.add('code-swap');}
function renderTypeSelect(){$('blockType').innerHTML=Object.entries(TYPES).map(([k,t])=>`<option value="${k}" ${state.currentType===k?'selected':''}>${esc(t.label)}</option>`).join('')}
function renderFields(){const t=TYPES[state.currentType]; $('targetHelp').innerHTML=`<b>${esc(t.target)}</b><br>${esc(t.help)}`; $('fields').innerHTML=t.fields.map(fieldHtml).join(''); $$('[data-field]').forEach(el=>{el.oninput=()=>{current()[el.dataset.field]=el.type==='checkbox'?el.checked:el.value; localStorage.setItem(KEY,JSON.stringify(state)); renderOutput();};});}
function renderStats(){const c={resource:0,creatorCard:0,profileHeader:0,profileResource:0,hubTile:0,newsBlock:0,newsSource:0,pageSection:0,navItem:0}; state.drafts.forEach(d=>c[d.type]=(c[d.type]||0)+1); const cats=new Set(state.drafts.filter(d=>d.type==='resource').map(d=>d.data.category)); const tabs=groupedDrafts().length; $('stats').innerHTML=[['Drafts',state.drafts.length],['Paste tabs',tabs],['Categories',cats.size],['Creators',c.creatorCard],['Profile items',c.profileResource],['Hub tiles',c.hubTile],['News posts',c.newsBlock],['News sources',c.newsSource],['Page blocks',c.pageSection]].map(([l,n])=>`<div class="stat"><b>${n}</b><span>${l}</span></div>`).join('');}
function renderDraftFilter(){const old=$('draftFilter').value||'all'; $('draftFilter').innerHTML=[['all','All types'],...Object.entries(TYPES).map(([k,t])=>[k,t.label])].map(([k,l])=>`<option value="${k}" ${old===k?'selected':''}>${esc(l)}</option>`).join('')}
function renderGroupTabs(){const root=$('groupTabs'); const groups=groupedDrafts(); if(!groups.length){root.innerHTML='<div class="tab-empty">No paste tabs yet</div>';return;} if(!state.activeGroup)state.activeGroup=groups[0].key; root.innerHTML=groups.map(g=>`<button class="browser-tab ${g.key===state.activeGroup?'active':''}" data-group="${esc(g.key)}"><span>${esc(g.label)}</span><b>${g.items.length}</b></button>`).join('')+`<button class="browser-tab all ${state.activeGroup==='__all'?'active':''}" data-group="__all"><span>All</span><b>${state.drafts.length}</b></button>`; $$('[data-group]',root).forEach(b=>b.onclick=()=>{state.activeGroup=b.dataset.group; localStorage.setItem(KEY,JSON.stringify(state)); render();});}
function draftTitle(d){const x=d.data; return d.type==='resource'?`${x.name||'Untitled'} · ${x.category||''}`:d.type==='creatorCard'?`${x.name||'Creator'} ${x.handle||''}`:d.type==='profileResource'?`${x.section} · ${x.name||'Resource'}`:d.type==='profileHeader'?`${x.creator||'Profile header'}`:d.type==='hubTile'?`${x.name||'Hub tile'}`:d.type==='newsSource'?`${x.title||'News source'}`:d.type==='pageSection'?`${x.title||'Page section'}`:d.type==='navItem'?`${x.title||'Menu item'}`:`${x.title||'News post'}`;}
function renderDrafts(){const ag=activeGroup(); let rows=(ag?.items||[]); const f=$('draftFilter').value||'all'; if(f!=='all')rows=rows.filter(x=>x.d.type===f); $('drafts').innerHTML=rows.length?rows.map(({d,i})=>{const g=groupMeta(d);return `<article class="draft"><div class="draft-top"><div><span class="tag">${esc(TYPES[d.type].label)}</span><span class="tag target-tag">${esc(g.label)}</span><strong>${esc(draftTitle(d))}</strong><p>${esc(g.target)}</p></div><div class="draft-actions"><button class="mini" data-edit="${i}">Edit</button><button class="mini" data-dupe="${i}">Duplicate</button><button class="mini danger" data-del="${i}">Remove</button></div></div></article>`}).join(''):`<div class="empty">No drafts in this tab.</div>`; $$('[data-del]').forEach(b=>b.onclick=()=>{state.drafts.splice(+b.dataset.del,1); const gs=groupedDrafts(); if(!gs.some(g=>g.key===state.activeGroup))state.activeGroup=gs[0]?.key||''; save();}); $$('[data-dupe]').forEach(b=>b.onclick=()=>{const d=JSON.parse(JSON.stringify(state.drafts[+b.dataset.dupe])); state.drafts.splice(+b.dataset.dupe+1,0,d); state.activeGroup=groupMeta(d).key; save();}); $$('[data-edit]').forEach(b=>b.onclick=()=>{const d=state.drafts[+b.dataset.edit]; state.currentType=d.type; state.form[d.type]=JSON.parse(JSON.stringify(d.data)); state.drafts.splice(+b.dataset.edit,1); state.activeGroup=groupedDrafts()[0]?.key||''; save();});}

function lineResource(x){return`  { name: ${js(x.name)}, link: ${js(x.link)}, desc: ${js(x.desc)}, cat: ${js(x.category)} },`}
function blockResource(items){const byPage=group(items,x=>x.data.page); return Object.entries(byPage).map(([page,rows])=>{const p=PAGES[page]||PAGES.custom; const byCat=group(rows,x=>x.data.category||'Uncategorized'); return `/* Target: ${p.file} → ${p.array} */\n`+Object.entries(byCat).map(([cat,rs])=>`  /* -------------------- ${cat.toUpperCase()} -------------------- */\n${rs.map(r=>lineResource(r.data)).join('\n')}`).join('\n\n');}).join('\n\n')}
function blockCreator(items){return`/* Target: creators.html → const CREATORS_DATA = [ ... ] */\n`+items.map(({data:x})=>`      {\n        id: ${Number(x.id)||1},\n        name: ${js(x.name)},\n        handle: ${js(x.handle)},\n        initials: ${js(x.initials)},\n        avatar: ${js(x.avatar)},\n        verified: ${!!x.verified},\n        category: ${js(x.category)},\n        bio: ${js(x.bio)},\n        links: ${Number(x.links)||0},\n        url: ${js(x.url)},\n        socials: {\n          x: ${js(x.x||'#')},\n          youtube: ${js(x.youtube||'#')},\n          github: ${js(x.github||'#')},\n          spotify: ${js(x.spotify||'#')},\n          apple_podcast: ${js(x.apple_podcast||'#')},\n          website: ${js(x.website||'#')}\n        }\n      },`).join('\n')}
function socialHtml(x){return [['X',x.x],['YouTube',x.youtube],['GitHub',x.github],['Website',x.website]].filter(([,u])=>u&&u!=='#').map(([n,u])=>`        <a href="${esc(u)}" class="social-icon" title="${esc(n)}" target="_blank" rel="noopener noreferrer">${esc(n)}</a>`).join('\n')||'        <!-- Add social icons here if needed -->'}
function blockProfileHeader(items){return items.map(({data:x})=>`<!-- Target: creators/${slug(x.creator)}.html → Profile Section -->\n    <div class="profile-section">\n      <div class="avatar-wrapper"><div class="avatar-ring"><div class="avatar-img"><img src="${esc(x.avatar)}" alt="${esc(x.creator)}"></div></div><div class="avatar-badge">✓</div></div>\n      <h1 class="profile-name">${esc(x.creator)}</h1>\n      <span class="profile-handle">${esc(x.handle)}</span>\n      <div class="social-links">\n${socialHtml(x)}\n      </div>\n    </div>`).join('\n\n')}
function blockProfileResource(items){const bySec=group(items,x=>x.data.section||'Resources'); return `/* Target: ${groupMeta(items[0]).target} */\n`+Object.entries(bySec).map(([section,rs])=>`      {\n        title: ${js(section)},\n        items: [\n${rs.map(({data:x})=>`          { name: ${js(x.name)}, desc: ${js(x.desc)}, img: ${js(x.img)}, url: ${js(x.url)}, tag: ${js(x.tag)} },`).join('\n')}\n        ]\n      },`).join('\n')}
function blockHub(items){return`/* Target: hub.html → const featuredData = [ ... ] */\n`+items.map(({data:x})=>`  { name: ${sq(x.name)}, desc: ${sq(x.desc)}, link: ${sq(x.link)}, icon: ${sq(x.icon)}${x.size?`, size: ${sq(x.size)}`:''} },`).join('\n')}
function blockNews(items){return items.map(({data:x})=>`<!-- Target: news.html → Project Changelog -->\n<div class="glass-card">\n  <span class="badge-date">${esc(x.date)}</span>\n  <h3>${esc(x.title)}</h3>\n  <p>${esc(x.body)}</p>${x.body2?`\n  <p>${esc(x.body2)}</p>`:''}${x.link?`\n  <p><a href="${esc(x.link)}" target="_blank" rel="noopener noreferrer">Learn more</a></p>`:''}\n</div>`).join('\n\n')}
function accentColor(a){return{blue:'var(--brand-light)',red:'#f87171',green:'#4ade80',purple:'#c084fc',yellow:'#facc15'}[a]||'var(--brand-light)'}
function blockNewsSource(items){return items.map(({data:x})=>`<!-- Target: news.html → <div class="news-grid"> -->\n<a href="${esc(x.link||'#')}" class="glass-card">\n  <div class="info-icon" style="background: rgba(12,132,243,0.15); border-color: rgba(12,132,243,0.2);">*</div>\n  <h3>${esc(x.title)}</h3>\n  <p>${esc(x.desc)}</p>\n  <div style="margin-top: auto; color: ${accentColor(x.accent)}; font-size: 0.8rem; font-weight: 600; text-transform: uppercase;">${esc(x.count)}</div>\n</a>`).join('\n\n')}
function blockPageSection(items){return items.map(({data:x})=>{const bullets=String(x.list||'').split(/\r?\n/).map(v=>v.trim()).filter(Boolean); return `<!-- Target: ${PAGES[x.page]?.file||'page.html'} → content area -->\n<section class="section">\n  <div class="container">\n    <div class="section-head">\n      <span class="section-kicker">${esc(x.kicker)}</span>\n      <h2 class="section-title">${esc(x.title)}</h2>\n    </div>\n    <div class="glass-card">\n      <p>${esc(x.body)}</p>${bullets.length?`\n      <ul>\n${bullets.map(b=>`        <li>${esc(b)}</li>`).join('\n')}\n      </ul>`:''}${x.link?`\n      <a href="${esc(x.link)}" target="_blank" rel="noopener noreferrer">${esc(x.linkLabel||'Learn more')}</a>`:''}\n    </div>\n  </div>\n</section>`}).join('\n\n')}
function blockNavItem(items){return items.map(({data:x})=>`<!-- Target: header/hamburger menu -->\n<a href="${esc(x.href)}" class="hamburger-item">\n  <div class="hamburger-icon"><!-- icon: ${esc(x.icon)} --></div>\n  <div class="hamburger-content">\n    <div class="hamburger-item-title">${esc(x.title)}</div>\n    <div class="hamburger-item-desc">${esc(x.desc)}</div>\n  </div>\n</a>`).join('\n\n')}
function generateItems(items){const byType=group(items,d=>d.type); const map={resource:blockResource,creatorCard:blockCreator,profileHeader:blockProfileHeader,profileResource:blockProfileResource,hubTile:blockHub,newsBlock:blockNews,newsSource:blockNewsSource,pageSection:blockPageSection,navItem:blockNavItem}; return Object.entries(byType).map(([t,arr])=>map[t](arr)).join('\n\n')}
function generate(scope){if(scope==='all'){const groups=groupedDrafts(); if(!groups.length)return'// No drafts for this output.'; return groups.map(g=>`/* ============================================================\n   TAB: ${g.label}\n   TARGET: ${g.target}\n============================================================ */\n`+generateItems(g.items.map(x=>x.d))).join('\n\n');} const g=activeGroup(); return g&&g.items.length?generateItems(g.items.map(x=>x.d)):'// No drafts in the active tab.';}
function renderOutput(){
  const all=$('outputScope').value==='all';
  const g=activeGroup();
  const active=document.querySelector('.code-tab.active .tab-title');
  $('targetText').textContent=all?'All tabs grouped separately':((active?active.textContent:(g?g.label:'No active tab'))+(g?' → '+g.target:''));
  $('code').textContent=generate(all?'all':'active');
}

function render(){renderTypeSelect();renderFields();renderStats();renderDraftFilter();renderGroupTabs();renderDrafts();renderCodeTabs();renderOutput();}

function validateData(type,x){const w=[]; if(['resource','creatorCard','profileResource','hubTile'].includes(type)&&!x.name)w.push('name missing'); if(type==='resource'&&!x.category)w.push('category missing'); for(const k of ['link','url','x','youtube','github','website','spotify','apple_podcast','href']) if(x[k]&&!urlOk(x[k]))w.push(`${k} looks invalid`); return w;}
function wire(){$('blockType').onchange=e=>{state.currentType=e.target.value;save()}; $('addDraft').onclick=()=>{const data=JSON.parse(JSON.stringify(current())); const warnings=validateData(state.currentType,data); if(warnings.length&&!confirm('Warnings: '+warnings.join(', ')+'. Add anyway?'))return; const draft={type:state.currentType,data,createdAt:new Date().toISOString()}; state.drafts.push(draft); state.activeGroup=groupMeta(draft).key; save(); pulseCode();}; $('clearForm').onclick=()=>{state.form[state.currentType]=JSON.parse(JSON.stringify(fresh().form[state.currentType]));save()}; $('draftFilter').onchange=renderDrafts; $('outputScope').onchange=renderOutput; $('clearDrafts').onclick=()=>{if(confirm('Clear all drafts?')){state.drafts=[];state.activeGroup='';save()}}; $('copyOutput').onclick=$('copyAllTop').onclick=async()=>{await navigator.clipboard.writeText($('code').textContent); const old=$('copyOutput').textContent; $('copyOutput').textContent='Copied';$('copyOutput').classList.add('copied');setTimeout(()=>{$('copyOutput').textContent=old;$('copyOutput').classList.remove('copied')},1000)}; $('downloadOutput').onclick=()=>{const blob=new Blob([$('code').textContent],{type:'text/plain;charset=utf-8'}); const a=document.createElement('a'); a.href=URL.createObjectURL(blob); a.download=(activeGroup()?.label||'bookmarks').replace(/[^a-z0-9]+/gi,'-').toLowerCase()+'-block.txt'; a.click(); URL.revokeObjectURL(a.href)}; $('exportWorkspace').onclick=()=>{const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'}); const a=document.createElement('a'); a.href=URL.createObjectURL(blob); a.download='bookmarks-admin-workspace.json'; a.click(); URL.revokeObjectURL(a.href)}; $('importWorkspace').onchange=async e=>{const f=e.target.files[0]; if(!f)return; state=merge(fresh(),JSON.parse(await f.text())); save()}; $('resetWorkspace').onclick=()=>{if(confirm('Reset local workspace?')){state=fresh();save()}};}
wire();render();

