const KEY='bookmarks-admin-min-v1';
const $=id=>document.getElementById(id);
const $$=(s,r=document)=>[...r.querySelectorAll(s)];
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const js=v=>`"${String(v??'').replace(/\\/g,'\\\\').replace(/"/g,'\\"').replace(/\r?\n/g,' ').trim()}"`;
const sq=v=>`'${String(v??'').replace(/\\/g,'\\\\').replace(/'/g,"\\'").replace(/\r?\n/g,' ').trim()}'`;
const slug=v=>String(v||'creator').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')||'creator';
const urlOk=v=>!v||v==='#'||/^(https?:\/\/|\/|mailto:|ipfs:\/\/|ftp:\/\/)/i.test(v);

const TYPES={
  resource:{label:'Site / resource link',target:'Home, Docs, Files, Jobs and similar pages',help:'Generates the { name, link, desc, cat } format used by bookmarks-data.js and by docs/files/jobs inline docsData arrays.',fields:[['page','select','Target page'],['category','text','Category'],['name','text','Site name'],['link','url','URL'],['desc','textarea','Description']]},
  creatorCard:{label:'Creator card',target:'creators.html → CREATORS_DATA',help:'Generates one creator object for the creators listing.',fields:[['id','number','ID'],['name','text','Creator name'],['handle','text','Handle'],['initials','text','Initials'],['avatar','text','Avatar path'],['verified','checkbox','Verified'],['category','text','Category'],['bio','textarea','Bio'],['links','number','Links count'],['url','text','Profile URL'],['x','url','X / Twitter'],['youtube','url','YouTube'],['github','url','GitHub'],['website','url','Website'],['spotify','url','Spotify'],['apple_podcast','url','Apple Podcast']]},
  profileHeader:{label:'Creator profile header',target:'creator profile page HTML',help:'Generates the profile section block for a page based on creators/profiletemplate.html.',fields:[['creator','text','Creator name'],['handle','text','Handle'],['avatar','text','Avatar path'],['x','url','X link'],['youtube','url','YouTube link'],['github','url','GitHub link'],['website','url','Website link']]},
  profileResource:{label:'Creator profile resource',target:'creator profile page → collectionData',help:'Generates resource items grouped inside a collectionData section.',fields:[['creator','text','Creator / profile'],['section','text','Section title'],['name','text','Resource name'],['desc','textarea','Description'],['img','text','Image path'],['url','url','URL'],['tag','text','Tag']]},
  hubTile:{label:'Hub tile',target:'hub.html → featuredData',help:'Generates one featuredData tile for the hub page.',fields:[['name','text','Tile name'],['desc','text','Short description'],['link','url','Link'],['icon','selectIcon','Icon'],['size','selectSize','Size']]},
  newsBlock:{label:'News / update HTML block',target:'news.html content area',help:'Generates a clean standalone news/update HTML section to paste into the news page content.',fields:[['title','text','Title'],['date','date','Date'],['category','text','Category'],['summary','textarea','Summary'],['body','textarea','Body paragraph'],['link','url','Optional link']]}
};
const PAGES={home:{label:'Home / Hub data',file:'data/bookmarks-data.js',array:'window.BOOKMARKS_DATA'},docs:{label:'Docs',file:'docs.html',array:'const docsData'},files:{label:'Files',file:'files.html',array:'const docsData'},jobs:{label:'Jobs',file:'jobs.html',array:'const docsData'},custom:{label:'Custom same-format page',file:'custom page',array:'same { name, link, desc, cat } array'}};
const ICONS=['file-text','download','github','users','briefcase','newspaper','heart','search','shield','book-open','globe','terminal'];
let state=load();function defaults(){return{currentType:'resource',drafts:[],form:{resource:{page:'home',category:'Search',name:'',link:'https://',desc:''},creatorCard:{id:1,name:'',handle:'@',initials:'',avatar:'/creators/img/avatar.jpg',verified:true,category:'Security',bio:'',links:0,url:'/creators/creator.html',x:'#',youtube:'#',github:'#',website:'#',spotify:'#',apple_podcast:'#'},profileHeader:{creator:'',handle:'@',avatar:'/creators/img/avatar.jpg',x:'#',youtube:'#',github:'#',website:'#'},profileResource:{creator:'',section:'Getting Started',name:'',desc:'',img:'',url:'#',tag:'Guide'},hubTile:{name:'',desc:'',link:'',icon:'file-text',size:''},newsBlock:{title:'',date:new Date().toISOString().slice(0,10),category:'Update',summary:'',body:'',link:''}}}}
function load(){try{return merge(defaults(),JSON.parse(localStorage.getItem(KEY)||'{}'))}catch{return defaults()}}function merge(a,b){for(const k in b){if(b[k]&&typeof b[k]==='object'&&!Array.isArray(b[k]))a[k]=merge(a[k]||{},b[k]);else a[k]=b[k]}return a}function save(){localStorage.setItem(KEY,JSON.stringify(state));render()}
function current(){return state.form[state.currentType]}
function fieldHtml([key,type,label]){const v=current()[key]??'';if(type==='textarea')return`<label>${label}<textarea data-field="${key}">${esc(v)}</textarea></label>`;if(type==='checkbox')return`<label class="check"><input type="checkbox" data-field="${key}" ${v?'checked':''}> ${label}</label>`;if(type==='select')return`<label>${label}<select data-field="${key}">${Object.entries(PAGES).map(([k,p])=>`<option value="${k}" ${v===k?'selected':''}>${esc(p.label)}</option>`).join('')}</select></label>`;if(type==='selectIcon')return`<label>${label}<select data-field="${key}">${ICONS.map(i=>`<option value="${i}" ${v===i?'selected':''}>${i}</option>`).join('')}</select></label>`;if(type==='selectSize')return`<label>${label}<select data-field="${key}"><option value="" ${!v?'selected':''}>Normal</option><option value="large" ${v==='large'?'selected':''}>Large</option></select></label>`;return`<label>${label}<input data-field="${key}" type="${type==='number'?'number':type==='date'?'date':'text'}" value="${esc(v)}"></label>`}
function renderTypeSelect(){$('blockType').innerHTML=Object.entries(TYPES).map(([k,t])=>`<option value="${k}" ${state.currentType===k?'selected':''}>${esc(t.label)}</option>`).join('')}
function renderFields(){const t=TYPES[state.currentType];$('targetHelp').innerHTML=`<b>${esc(t.target)}</b><br>${esc(t.help)}`;$('fields').innerHTML=t.fields.map(fieldHtml).join('');$$('[data-field]').forEach(el=>{el.oninput=()=>{const k=el.dataset.field;current()[k]=el.type==='checkbox'?el.checked:el.value;localStorage.setItem(KEY,JSON.stringify(state));renderOutput()}})}
function renderStats(){const counts={resource:0,creatorCard:0,profileHeader:0,profileResource:0,hubTile:0,newsBlock:0};state.drafts.forEach(d=>counts[d.type]=(counts[d.type]||0)+1);const cats=new Set(state.drafts.filter(d=>d.type==='resource').map(d=>d.data.category));const pages=new Set(state.drafts.filter(d=>d.type==='resource').map(d=>d.data.page));$('stats').innerHTML=[['Drafts',state.drafts.length],['Resource pages',pages.size],['Categories',cats.size],['Creators',counts.creatorCard],['Profile items',counts.profileResource],['Hub tiles',counts.hubTile]].map(([l,n])=>`<div class="stat"><b>${n}</b><span>${l}</span></div>`).join('')}
function renderDraftFilter(){const opts=[['all','All drafts'],...Object.entries(TYPES).map(([k,t])=>[k,t.label])];$('draftFilter').innerHTML=opts.map(([k,l])=>`<option value="${k}">${esc(l)}</option>`).join('')}
function draftTitle(d){const x=d.data;return d.type==='resource'?`${PAGES[x.page]?.label||x.page} / ${x.category} · ${x.name||'Untitled'}`:d.type==='creatorCard'?`${x.name||'Creator'} ${x.handle||''}`:d.type==='profileResource'?`${x.creator||'Profile'} / ${x.section} · ${x.name||'Resource'}`:d.type==='profileHeader'?`${x.creator||'Profile header'}`:d.type==='hubTile'?`${x.name||'Hub tile'}`:`${x.title||'News block'}`}
function renderDrafts(){const f=$('draftFilter').value||'all';const rows=state.drafts.map((d,i)=>({d,i})).filter(x=>f==='all'||x.d.type===f);$('drafts').innerHTML=rows.length?rows.map(({d,i})=>`<article class="draft"><div class="draft-top"><div><span class="tag">${esc(TYPES[d.type].label)}</span><strong>${esc(draftTitle(d))}</strong><p>${esc(TYPES[d.type].target)}</p></div><div class="draft-actions"><button class="mini" data-edit="${i}">Edit</button><button class="mini" data-dupe="${i}">Duplicate</button><button class="mini danger" data-del="${i}">Remove</button></div></div></article>`).join(''):`<div class="empty">No drafts yet. Fill the form and click Add to drafts.</div>`;$$('[data-del]').forEach(b=>b.onclick=()=>{state.drafts.splice(+b.dataset.del,1);save()});$$('[data-dupe]').forEach(b=>b.onclick=()=>{state.drafts.splice(+b.dataset.dupe+1,0,JSON.parse(JSON.stringify(state.drafts[+b.dataset.dupe])));save()});$$('[data-edit]').forEach(b=>b.onclick=()=>{const d=state.drafts[+b.dataset.edit];state.currentType=d.type;state.form[d.type]=JSON.parse(JSON.stringify(d.data));state.drafts.splice(+b.dataset.edit,1);save()})}
function lineResource(x){return`  { name: ${js(x.name)}, link: ${js(x.link)}, desc: ${js(x.desc)}, cat: ${js(x.category)} },`}function blockResource(items){const byPage=group(items,x=>x.data.page);return Object.entries(byPage).map(([page,rows])=>{const p=PAGES[page]||PAGES.custom;const byCat=group(rows,x=>x.data.category||'Uncategorized');return`/* Target: ${p.file} → ${p.array} */\n`+Object.entries(byCat).map(([cat,rs])=>`  /* -------------------- ${cat.toUpperCase()} -------------------- */\n${rs.map(r=>lineResource(r.data)).join('\n')}`).join('\n\n')}).join('\n\n')}
function blockCreator(items){return`/* Target: creators.html → const CREATORS_DATA = [ ... ] */\n`+items.map(({data:x})=>`      {\n        id: ${Number(x.id)||1},\n        name: ${js(x.name)},\n        handle: ${js(x.handle)},\n        initials: ${js(x.initials)},\n        avatar: ${js(x.avatar)},\n        verified: ${!!x.verified},\n        category: ${js(x.category)},\n        bio: ${js(x.bio)},\n        links: ${Number(x.links)||0},\n        url: ${js(x.url)},\n        socials: {\n          x: ${js(x.x||'#')},\n          youtube: ${js(x.youtube||'#')},\n          github: ${js(x.github||'#')},\n          spotify: ${js(x.spotify||'#')},\n          apple_podcast: ${js(x.apple_podcast||'#')},\n          website: ${js(x.website||'#')}\n        }\n      },`).join('\n')}
function socialHtml(x){return [['X',x.x],['YouTube',x.youtube],['GitHub',x.github],['Website',x.website]].filter(([,u])=>u&&u!=='#').map(([n,u])=>`        <a href="${esc(u)}" class="social-icon" title="${esc(n)}" target="_blank" rel="noopener noreferrer">${esc(n)}</a>`).join('\n')||'        <!-- Add social icons here if needed -->'}
function blockProfileHeader(items){return items.map(({data:x})=>`<!-- Target: creators/${slug(x.creator)}.html → Profile Section -->\n    <div class="profile-section">\n      <div class="avatar-wrapper">\n        <div class="avatar-ring">\n          <div class="avatar-img">\n            <img src="${esc(x.avatar)}" alt="${esc(x.creator)}">\n          </div>\n        </div>\n        <div class="avatar-badge">✓</div>\n      </div>\n      <h1 class="profile-name">${esc(x.creator)}</h1>\n      <span class="profile-handle">${esc(x.handle)}</span>\n      <div class="social-links">\n${socialHtml(x)}\n      </div>\n    </div>`).join('\n\n')}
function blockProfileResource(items){const byCreator=group(items,x=>x.data.creator||'creator');return Object.entries(byCreator).map(([creator,rows])=>{const bySec=group(rows,x=>x.data.section||'Resources');return`/* Target: creators/${slug(creator)}.html → const collectionData = [ ... ] */\n`+Object.entries(bySec).map(([section,rs])=>`      {\n        title: ${js(section)},\n        items: [\n${rs.map(({data:x})=>`          { name: ${js(x.name)}, desc: ${js(x.desc)}, img: ${js(x.img)}, url: ${js(x.url)}, tag: ${js(x.tag)} },`).join('\n')}\n        ]\n      },`).join('\n')}).join('\n\n')}
function blockHub(items){return`/* Target: hub.html → const featuredData = [ ... ] */\n`+items.map(({data:x})=>`  { name: ${sq(x.name)}, desc: ${sq(x.desc)}, link: ${sq(x.link)}, icon: ${sq(x.icon)}${x.size?`, size: ${sq(x.size)}`:''} },`).join('\n')}
function blockNews(items){return items.map(({data:x})=>`<!-- Target: news.html content area -->\n<section class="news-update">\n  <div class="category-tag">${esc(x.category)}</div>\n  <h2>${esc(x.title)}</h2>\n  <time datetime="${esc(x.date)}">${esc(x.date)}</time>\n  <p><strong>${esc(x.summary)}</strong></p>\n  <p>${esc(x.body)}</p>\n  ${x.link?`<a href="${esc(x.link)}" target="_blank" rel="noopener noreferrer">Read more</a>`:''}\n</section>`).join('\n\n')}
function group(arr,fn){return arr.reduce((a,x)=>{const k=fn(x)||'Other';(a[k]||=[]).push(x);return a},{})}
function generate(type){const items=state.drafts.filter(d=>type==='all'||d.type===type);if(!items.length)return'// No drafts for this output.';if(type==='all')return Object.keys(TYPES).map(k=>generate(k)).filter(x=>!x.startsWith('// No')).join('\n\n');return({resource:blockResource,creatorCard:blockCreator,profileHeader:blockProfileHeader,profileResource:blockProfileResource,hubTile:blockHub,newsBlock:blockNews})[type](items)}
function renderOutput(){const scope=$('outputScope').value;const type=scope==='all'?'all':state.currentType;$('targetText').textContent=scope==='all'?'All drafts grouped by target':TYPES[state.currentType].target;$('code').textContent=generate(type)}
function render(){renderTypeSelect();renderFields();renderStats();renderDraftFilter();renderDrafts();renderOutput()}
function validateData(type,x){const w=[];if(['resource','creatorCard','profileResource','hubTile'].includes(type)&&!x.name)w.push('name missing');if(type==='resource'&&!x.category)w.push('category missing');for(const k of ['link','url','x','youtube','github','website','spotify','apple_podcast'])if(x[k]&&!urlOk(x[k]))w.push(`${k} looks invalid`);return w}
function wire(){$('blockType').onchange=e=>{state.currentType=e.target.value;save()};$('addDraft').onclick=()=>{const data=JSON.parse(JSON.stringify(current()));const warnings=validateData(state.currentType,data);if(warnings.length&&!confirm('Warnings: '+warnings.join(', ')+'. Add anyway?'))return;state.drafts.push({type:state.currentType,data,createdAt:new Date().toISOString()});save()};$('clearForm').onclick=()=>{state.form[state.currentType]=JSON.parse(JSON.stringify(defaults().form[state.currentType]));save()};$('draftFilter').onchange=renderDrafts;$('outputScope').onchange=renderOutput;$('clearDrafts').onclick=()=>{if(confirm('Clear all drafts?')){state.drafts=[];save()}};$('copyOutput').onclick=$('copyAllTop').onclick=async()=>{await navigator.clipboard.writeText($('code').textContent);const old=$('copyOutput').textContent;$('copyOutput').textContent='Copied';setTimeout(()=>$('copyOutput').textContent=old,1000)};$('downloadOutput').onclick=()=>{const blob=new Blob([$('code').textContent],{type:'text/plain;charset=utf-8'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='bookmarks-generated-blocks.txt';a.click();URL.revokeObjectURL(a.href)};$('exportWorkspace').onclick=()=>{const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='bookmarks-admin-workspace.json';a.click();URL.revokeObjectURL(a.href)};$('importWorkspace').onchange=async e=>{const f=e.target.files[0];if(!f)return;state=merge(defaults(),JSON.parse(await f.text()));save()};$('resetWorkspace').onclick=()=>{if(confirm('Reset local workspace?')){state=defaults();save()}}}
wire();render();

